---
- name: Check Disk Space on Linux
  hosts: your_servers  # Replace 'your_servers' with the appropriate host/group

  tasks:
    - name: Run df -h command to check disk space
      become: yes  # This ensures running the command with elevated privileges
      command: df -h
      register: disk_space_output  # Stores the output of the command in a variable

    - name: Display disk space information
      debug:
        var: disk_space_output.stdout_lines  # Display the output of the df -h command
