---
- name: Check Disk Space of All Directories on Linux
  hosts: all 

  tasks:
    - name: Get disk space for all directories
      become: yes  
      shell: "df -h"
      register: disk_space_output  

    - name: Display disk space information for all directories
      debug:
        var: disk_space_output.stdout_lines  
