---
- name: Check Server Uptime
  hosts: all
  gather_facts: true

  tasks:
    - name: Get server uptime
      command: uptime
      register: uptime_output

    - name: Display server uptime
      debug:
        msg: "Server Uptime: {{ uptime_output.stdout }}"
